openapi: 3.0.0
info:
  version: 1.0.0
  title: ESZT - Egészségügyi Szuri Tár
  description: Beoltott személyek adatainak nyilvántartása
servers:
  - url: http://localhost:3000
paths:
  /person/count:
    get:
      description: Returns the number of vaccinated people
      responses:
        '200':
          description: Number of vaccinated people returned successfully
          content:
            application/json:
              schema:
                type: integer
  /person/vaccinated:
    get:
      description: Returns all data of vaccinated people
      responses:
        '200':
          description: All data of vaccinated people returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
components:
  schemas:
    Person:
      type: object
      required:
        - firstName
        - lastName
        - vaccine
      properties:
        firstName:
          type: string
        lastName:
          type: string
        vaccine:
          type: string